APP_VERSION = "1.27.3"
APPLICATION_TITLE = f"Image Vectorizer v{APP_VERSION}"
APP_NAME = "Silukman Image Vectorizer"
SIDEBAR_TITLE = "Sidebar"
PREVIEW_AREA_TITLE = "Preview Area"
CONTROL_PANEL_TITLE = "Control Panel"
STATUS_READY = "Ready"
